// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhplzwvisroexpjfdmqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocGx6d3Zpc3JvZXhwamZkbXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyMDk1NDIsImV4cCI6MjA5NDc4NTU0Mn0.nlPAeRNSJY_y3ZxawUbUJq-VtL3LX-LVv7hbMloT_ig";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
